### PR TITLE
:arrow_up: updating base image to 1-68

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by VannTen** [comment]
same comment and question than #253

**Comment by goern** [comment]
this and #253 could be released as v0.35.0 after merge...

**Review by VannTen — APPROVED** [review]
/lgtm

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
thanks :+1:

**Pull request merged**
