### PR TITLE
WIP: removed the network curl call from the ubi8-py36

### PR DESCRIPTION
**Pull request by harshad16**
## Related Issues and Dependencies

Related-to: #124 

## This Pull Request implements

removed the network curl call from the ubi8-py36
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Description

For building the s2i-thoth image in a building service that restricts certain network calls.

### CODE REVIEW

**Comment by harshad16** [comment]
/hold 

This PR is for discussions only.

**Comment by harshad16** [comment]
In this way we would have to reconfigure our quay build trigger to build from root context dir.

**Comment by goern** [comment]
lgtm, @fridex  ?

**Comment by fridex** [comment]
> lgtm, @fridex ?

I would keep this decision on @harshad16 if he is fine with it. Let's see what is the best option here with respect to dist-git handling so we do not introduce problematic integration.

Thanks, @harshad16 for work on this :+1:

**Comment by goern** [comment]
what do we need to get this done?

**Pull request closed without merging**
