### PR TITLE
Bump micropipenv and thamos versions

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until https://github.com/thoth-station/thamos/issues/571 gets merged and the release is done.

**Review by harshad16 — COMMENTED** [review]
lgtm :100: 
thanks for the update :) 
can you please update the version of thoth-s2i https://github.com/thoth-station/s2i-thoth/blob/90c7c2cabdb5f7ab0a31bd60afc52fa2dfc0895e/f31-py37/Dockerfile#L6 in all files as well
so that when we release, the image corresponds to the version specified in dockerfile.

**Comment by fridex** [comment]
Agh, I always forget it. Thanks for pointing this out :+1: good catch!

**Review by harshad16 — APPROVED** [review]
Thanks :100:

**Pull request merged**
