### PR TITLE
Update to thamos v1.24.0

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by codificat** [comment]
By now, we probably want the latest tag (`v1.27.2`) instead, right?

About the pre-commit failure: a quick check here reports that the remove-tabs hook is not happy with the `ubi*/s2i_assemble.patch` files.

**Comment by goern** [comment]
@Gregory-Pereira maybe you can work on this too?

**Comment by Gregory-Pereira** [comment]
> @Gregory-Pereira maybe you can work on this too?

:+1: 
/assign

**Comment by fridex** [comment]
Oh, nice. I will close this PR as it will most probably need an update of deps in a separate pr.

**Pull request closed without merging**
